//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUZEY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islemler
    {
        public int id { get; set; }
        public string Firmaid { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string FirmaPersonel { get; set; }
        public string ACGrafi { get; set; }
        public string Odyo { get; set; }
        public string SFT { get; set; }
        public string EKG { get; set; }
        public string Hemogram { get; set; }
        public string Biyokimya { get; set; }
        public string Burun { get; set; }
        public string Bogaz { get; set; }
        public string Gaita { get; set; }
        public string Tetanoz { get; set; }
        public string KanGrubu { get; set; }
        public string Hepatit { get; set; }
        public string Portor { get; set; }
        public string Idrar { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> Nakit { get; set; }
        public Nullable<decimal> Pos { get; set; }
        public string Ekleyen { get; set; }
        public Nullable<System.DateTime> EklemeTarihi { get; set; }
        public string Kontrol { get; set; }
        public Nullable<System.DateTime> KontrolTarihi { get; set; }
        public string Muhasebelestiren { get; set; }
        public Nullable<System.DateTime> MuhTarihi { get; set; }
        public Nullable<System.DateTime> FaturaTarihi { get; set; }
        public string FaturaNo { get; set; }
    }
}
