//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUZEY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KUZEYEntities : DbContext
    {
        public KUZEYEntities()
            : base("name=KUZEYEntities")
        {
        }
        public KUZEYEntities(string conStr)
                : base(conStr)
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Firma> Firma { get; set; }
        public virtual DbSet<Islemler> Islemler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Sbt_OdemeTip> Sbt_OdemeTip { get; set; }
        public virtual DbSet<Sbt_YetkiTip> Sbt_YetkiTip { get; set; }
        public virtual DbSet<VW_FIRMA> VW_FIRMA { get; set; }
        public virtual DbSet<VW_KULLANICI> VW_KULLANICI { get; set; }
    }
}
