//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUZEY
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FIRMA
    {
        public int Id { get; set; }
        public string FirmaAdi { get; set; }
        public string FirmaAdres { get; set; }
        public string FirmaTelefon { get; set; }
        public string FirmaIlgili { get; set; }
        public string FirmaMail { get; set; }
        public string FirmaGSM { get; set; }
        public string FirmaIlce { get; set; }
        public string FirmaIl { get; set; }
        public string FirmaAnlasma { get; set; }
        public Nullable<int> FirmaOdemeTip { get; set; }
        public string OdemeTip { get; set; }
    }
}
