//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUZEY
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_KULLANICI
    {
        public int Id { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSifre { get; set; }
        public Nullable<int> YetkiTip { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public string Yetki { get; set; }
    }
}
